### PR TITLE
more trimming, no AOT

### PR DESCRIPTION
**Pull request by pavelsavara**
This trims it down to 882kb .br compressed

### CODE REVIEW

**Comment by pavelsavara** [comment]
I also created https://github.com/dotnet/runtime/issues/110840 which are possible improvement on the runtime side

**Review by DamianEdwards — APPROVED** [review]
Thanks! Is there any support for native AOT on WebAssembly as yet?

**Comment by maraf** [comment]
> Thanks! Is there any support for native AOT on WebAssembly as yet?

Experimental community-driven project https://github.com/dotnet/runtimelab/tree/feature/NativeAOT-LLVM

**Comment by pavelsavara** [comment]
> Thanks! Is there any support for native AOT on WebAssembly as yet?

https://github.com/DamianEdwards/WasmClientSideValidation/pull/3

**Pull request merged**
